name: Switch game deals with scores
description: Find out is it worth buying the game or not
meta_description: "Find out is it worth buying the game or not"

markdown: kramdown
highlighter: rouge
github: [metadata]
logo: true 
paginate_path: "page:num"
timezone: CZ
domain_name: ''
baseurl:
plugins:
  - jekyll-feed

paginate: 7
collections: 
 breakfasts:
  output: true

author:  'Yuriy Shiryaev'
twitter: 'yuriysteam'


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/